### ISSUE TITLE
upgrade_iredadmin.sh fails on FreeBSD 13

### ISSUE THREAD

**Issue by elchy** [iredmail/iRedAdmin#17]
`KERNEL_NAME="$(uname -s | tr '[a-z]' '[A-Z]')"` obviously doesn't work on FreeBSD (13.0-RELEASE-p4, current port tree). I replaced that with `export KERNEL_NAME="$(uname -s | tr '[:lower:]' '[:upper:]')"` to fix this.

On FreeBSD, the script checks for `CMD_PIP3='/usr/local/bin/pip3'` but the port `devel/py-pip` doesn't install that file but only `/usr/local/bin/pip` which is a symlink to `/usr/local/bin/pip-3.8`.

**Comment by iredmail** [comment]
Invalid issue.
