### ISSUE TITLE
Receipients limiting BCC / CC / TO

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedAdmin#20]
The best situation I think is to set limit to not more than 10 receipients in CC/TO/ANSWERTO and not more than 100 in total.
Is it possible to set a limit of maximum receipients in one mail on domain/user level with iredadmin?
I would like to prevent peoples possible mistakes when putting many BCC mails in CC.

**Comment by iredmail** [comment]
FYI: http://www.postfix.org/postconf.5.html#default_recipient_limit

**Comment by interduo** [comment]
@iredmail I know that setting - This is global server setting.  It's not the way because we will block sending daily mails from management. Did You understand what I mean? Maybe there is some workaround for not to block that?

**Comment by iredmail** [comment]
Oh, misunderstood.

For per-domain and per-user setting, please use iRedAPD plugin `throttle`, read the code comment lines here to understand what it does and sample settings: https://github.com/iredmail/iRedAPD/blob/master/plugins/throttle.py

With iRedAdmin-Pro, you can set per-domain and per-user throttle in account profile page.

**Comment by interduo** [comment]
I see throttle settings but I do not see receipient limits on 4.9 version.
Could You show me this on screenshot?

**Comment by iredmail** [comment]
Check the selected text in screenshot.
<img width="591" alt="Screen Shot 2022-04-20 at 11 03 12 AM" src="https://user-images.githubusercontent.com/2048991/164141954-a368927c-996a-417b-b61b-446912d0f960.png">
