### ISSUE TITLE
iRedAdminPro: unsubscription of mailing list options unclear labels

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedAdmin#22]
Now there is: ![image](https://user-images.githubusercontent.com/17087236/167122163-7c88a7c0-269e-472c-b2db-c760dc82e53c.png)

First two options are exclusive.

My suggestion is:
```
Email subscription control (membership to maillist):
[x] allow subscription,
[x] allow unsubscription,
[x] subscription confirm
```

**Comment by iredmail** [comment]
Sorry i prefer current descriptions. :)

**Comment by interduo** [comment]
Those two checkboxes are excluded eatch others in some parts:
Could You describe me the bevahe of iredadmin when we check this two checkboxes?

**Comment by iredmail** [comment]
Please check parameter `closedlist` and `closedlistsub` here:
http://mlmmj.org/docs/tunables/

- `closedlist` is same as `Disable subscription and unsubscription`.
- `closedlistsub` is same as `Disable subscription but allow unsubscription`.

**Comment by interduo** [comment]
Thanks for references.
