### ISSUE TITLE
After upgrading to 1.8 I get "SyntaxError: invalid syntax" in /opt/www/iredadmin/libs/iredutils.py

### ISSUE THREAD

**Issue by jesperkp** [iredmail/iRedAdmin#24]
After an upgrade to version 1.8 I get the following error in my Apache logs:

```
mod_wsgi (pid=31017): Exception occurred processing WSGI script '/opt/www/iredadmin/iredadmin.py'.
Traceback (most recent call last):
File "/opt/www/iredadmin/iredadmin.py", line 8, in <module>
     from libs import iredbase
   File "/opt/www/iredadmin/libs/iredbase.py", line 18, in <module>
     from . import iredutils
   File "/opt/www/iredadmin/libs/iredutils.py", line 54
     def is_auth_email(s) -> bool:
                          ^
 SyntaxError: invalid syntax
```

I am running my iRedMailAdmin on a Debian 9 server

**Comment by jesperkp** [comment]
The problem was identified to be a needed replacement of the Apache WSGI module from libapache2-mod-wsgi to libapache2-mod-wsgi-py3 which did not happen automatically.

**Comment by iredmail** [comment]
Debian 9 is EOF, please upgrade to 11. :)

**Comment by iredmail** [comment]
FYI https://wiki.debian.org/LTS

> Debian LTS support for Debian 9 "Stretch" ended on June 30, 2022
>
> ... Debian LTS is not handled by the Debian Security team, but by a separate group of volunteers and companies interested in making it a success.
