### ISSUE TITLE
amavisd.msgs not cleaned with quar_type IS NULL

### ISSUE THREAD

**Issue by jbender81** [iredmail/iRedAdmin#25]
The cleanup statements check for quar_type = 'Q' and quar_type <> 'Q', neither match for quar_type IS NULL.
That has the effect, that those entries start to accumulate over time.

**Comment by iredmail** [comment]
I suppose `quar_type <> 'Q'` matches `quar_type is null`.

How many records does it accumulate till now on your server?

**Comment by jbender81** [comment]
Hi,
At the moment that are only 232 records in the msgs table:
select from_unixtime(min(time_num)),from_unixtime(max(time_num)),count(*) from msgs where quar_type is null \G
*************************** 1. row ***************************
from_unixtime(min(time_num)): 2020-03-25 07:10:22
from_unixtime(max(time_num)): 2022-11-21 07:10:33
                    count(*): 232
1 row in set (0.001 sec)

**Comment by iredmail** [comment]
Is it possible to get a copy of the `amavisd` sql database for local testing?
If yes, please dump and compress it, then mail to me: zhb _at_ iredmail.org

**Comment by jbender81** [comment]
Hi,
Unfortunatelly that is not possible due to data privacy.

**Comment by iredmail** [comment]
Hi @jbender81 

This issue has been fixed moment ago, you can either apply the patch for iRedAdmin-2.1, or download iRedAdmin-2.2 then upgrade to fix it. 

Thanks again for the feedback. :)
