### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by christophe-riolo** [iredmail/iRedAdmin#26]
Hello,

I have just started with iRedMail, and I was thinking that maybe it would be safer to have a 2FA solution for the admin portal, as it seems to me like a potential security risk?

Thanks for the great products 🙏

**Comment by iredmail** [comment]
Already on my todo list, but current focus is the upcoming iRedMail Pro[1], so it will be delayed.

[1] https://docs.iredmail.org/pro.html
