### ISSUE TITLE
autoresponder

### ISSUE THREAD

**Issue by joksik** [iredmail/iRedAdmin#30]
Hello i use iRedAdmin-Pro. I often feel the lack of an autoresponder option. Currently, to set this option, I need to know the employee's password and log in to the roundcube mailbox for him. If you can add such an option in the future. I think it will improve the work of many people.

**Comment by iredmail** [comment]
> I need to know the employee's password and log in to the roundcube mailbox for him.

You can login as Dovecot Master User, no need to know employee's password. https://docs.iredmail.org/dovecot.master.user.html

No plan to add autoresponder in iRedAdmin-Pro shortly, sorry. :(

**Comment by joksik** [comment]
Unfortunately, I do not have access to the server via ssh, only via www to the panel.
I'll wait then.
