### ISSUE TITLE
Allow to set autoresponder by administrator (completly enable/disable/configure sieve filters)

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedAdmin#7]
When some employee is very ill or had an accident in work. There is a need to set autoresponder by admin when the employee could not do this by himself.

This would also help to debug "lost mails" (said by users) and "bad sieve filter settings" (described by admin) :-)

This is an proposal of enhancement, not a bug issue.

**Comment by iredmail** [comment]
As a temporary solution, you can login to user’s mailbox with Dovecot Master User (and webmail):
https://docs.iredmail.org/dovecot.master.user.html

**Comment by interduo** [comment]
Good simple workaround.

**Comment by interduo** [comment]
Do you know is it possibile to mount all mail boxes together by imap using dovecot master user?

**Comment by iredmail** [comment]
- What does the "mount" mean?
- Dovecot master user can access all users' mailboxes.

**Comment by interduo** [comment]
Show all mailboxes in imap client (thunderbird).


Do you plan to implement this function są first post in future?

**Comment by iredmail** [comment]
- I don't know how to "mount" this way.
- No plan yet. sorry.

**Comment by interduo** [comment]
Thanks for info.
